@startuml 演習2-8
left to right direction
actor 利用者
actor ホテル従業員
actor ホテルの管理者

rectangle ホテルシステム {
  利用者 --> (ホテルの空室状況を閲覧する)
  利用者 --> (ホテルの部屋を予約する)
  (ホテルの空室状況を入力する) <-- ホテル従業員
  (予約の集計を行う) <-- ホテルの管理者
  (ログインする) <-- 利用者
  (会員登録を行う) <-- 利用者
  (宿泊費をキャンペーン価格に設定する) <-- ホテルの管理者
  (ログインする) <-- ホテル従業員
  (ログインする) <-- ホテルの管理者
  (会員登録を行う) <-- (ホテルの部屋を予約する)
  (会員登録を行う) <-- (ホテルの空室状況を閲覧する)
}
@enduml
