@startuml 演習7-4-1

class ドリンク {
    +種類
    +サイズ
}

class フード {
    +種類
}

class 商品 {
    +名称
    +単価
}

class 注文明細 {
    +商品
    +数量
}

class 注文 {
    +注文明細[]
    +合計金額
}

class カップ {
    +サイズ
}

class 材料 {
    +名前
}

class ハンバーガー {
    +材料[]
}

class 割引クーポン {
    +割引額
    +期限
}

class レシピ {
    +材料[]
}

class ポテト {
    +種類
}

ドリンク --> カップ
フード --> ハンバーガー
フード --> ポテト
商品 <|-- ドリンク
商品 <|-- フード
注文明細 "1" *-- "1" 商品
注文 "1" *-- "*" 注文明細
ハンバーガー "1" -- "*" 材料
割引クーポン -- 注文
レシピ "1" -- "*" 材料
ポテト --> フード

@enduml
