@startuml 演習4-3

participant "データ更新コントローラ" as controller
participant "ホテル" as hotel
participant "予約" as reservation <<create>>

controller -> hotel: 予約操作を呼び出す
activate hotel
hotel -> hotel: 予約オブジェクトを作成する
hotel -> reservation: 予約操作を呼び出す
activate reservation
reservation -> reservation: 予約登録（再帰呼出）
reservation --> hotel: 予約結果を返す
deactivate reservation
hotel --> controller: 予約結果を返す
deactivate hotel

@enduml
