@startuml 演習3-5

class ホテル {
}

class 部屋 {
  - 客室番号
  - 客室タイプ
  - 客室料
}

class キャンペーン {
  - 開始日
  - 終了日
  - キャンペーン価格
}

class 利用者 {
  - 利用者名
  - チェックイン日
  - 宿泊期間
}

ホテル o-- 部屋
ホテル o-- キャンペーン
ホテル o-- 利用者

部屋 *-- 利用者: 予約
キャンペーン -- 部屋: 適用される対象

@enduml
