@startuml 演習2-8
left to right direction

actor 利用者 
actor ホテル従業員 
actor 管理者 

rectangle システム {
  usecase ログイン 
  usecase 会員登録 
  usecase 会員
  usecase 空室状況閲覧 
  usecase 部屋予約 
  usecase 空室状況入力
  usecase 予約集計 
  usecase キャンペーン価格
  usecase キャンペーン期間中の宿泊 

  利用者 --> ログイン
  利用者 --> 空室状況閲覧
  ログイン --> 部屋予約
  ホテル従業員 --> ログイン
  ログイン --> 空室状況入力
  管理者 --> ログイン
  ログイン --> 予約集計 

  利用者 --> 会員登録
  会員登録 --> 会員
  会員 --|> ログイン

  利用者 --> キャンペーン期間中の宿泊
  キャンペーン期間中の宿泊 --> キャンペーン価格
  
}

@enduml
