@startuml 演習3-6

class 高橋洋平 {
    - 資格
    - 申請日: 2020年10月21日
}

class 樋口正之 {
    - 資格
}

class LinuC試験Level1 {
    - 資格名: "LinuC試験Level1"
}

高橋洋平 --> 情報処理安全確保支援士試験 : 合格
樋口正之 --> 情報処理安全確保支援士試験 : 合格
高橋洋平 --> LinuC試験Level1 : 合格
@enduml
