@startuml 演習6-5ユースケース図
left to right direction

rectangle ライントレーサーシステム {
  ユーザー -- (ライントレーサーを操作する)
  (ライントレーサーを操作する) --> (システムを起動する)
  (ライントレーサーを操作する) --> (システムを停止する)
  光センサー -- (ラインの状態を検知する)
  (ラインの状態を検知する) --> (右旋回を開始する)
  (ラインの状態を検知する) --> (左旋回を開始する)
  右モータ -- (右旋回を開始する)
  左モータ -- (左旋回を開始する)
  電源SW -- (システムを起動する)
  電源SW -- (システムを停止する)
}

@enduml
