@startuml 4-2

participant User as user
participant ReservationScreen as reservationScreen

user -> reservationScreen: ログイン (非同期)
activate user
activate reservationScreen
user <-- reservationScreen: ログインメッセージを返す (非同期)
deactivate reservationScreen
deactivate user

user -> reservationScreen: 確認操作の呼び出し (同期)
activate user
activate reservationScreen
user -> reservationScreen: 認証する (同期)
activate reservationScreen
user <-- reservationScreen: 認証結果を返す (同期)
deactivate reservationScreen
deactivate user

@enduml
